#-----------------------------------
#Database Login Data
#-----------------------------------
Host: ''
Username: ''
Password: ''
Port: ''

#-----------------------------------
#File Path
#-----------------------------------
DefaultFortPath: '/DefaultForts/defaultFort.schem'
SoloFortPath: '/Solo/Forts/'
SoloFortConfigPath: '/Solo/Configs/'

#-----------------------------------
#Fort Settings
#-----------------------------------
BlocksBetweenForts: 300

FortSizeX: 100.0
FortSizeY: 100.0
FortSizeZ: 100.0