#Database Login
Host: ''
Username: ''
Password: ''
Port: ''

#Schematics Path
DefaultFortPath: '/Forts/DefaultForts/defaultFort.schem'
SoloFortPath: '/Forts/SoloForts/'

#Fort Settings
BlocksBetweenForts: 300

FortSizeX: 100.0
FortSizeY: 100.0
FortSizeZ: 100.0