name: FortGame
version: '${project.version}'
main: com.therift.fortgame.Main
api-version: 1.19
authors: [ TheRift ]
description: A minigame form TheRift Server
depend: [WorldEdit, TheRiftCore]
commands:
  ForceSave:
    permission: "fortgame.forcesave"
    description: "Save the giving fort"
