name: FortGame
version: '${project.version}'
main: com.therift.fortgame.Main
api-version: 1.19
authors: [ TheRift ]
description: A minigame form TheRift Server
depend: [WorldEdit]
commands:
  ForceSoloSave:
    permission: "fortgame.forcesolosave"
    description: "Save the giving fort"
  ForceSoloLoad:
    permission: "fortgame.forcesoloload"
    description: "Loads the giving fort"
  ForceSoloDelete:
    permission: "fortgame.forcesolodelete"
    description: "delete the giving fort"
  Invite:
    permission: "fortgame.multiplayer.invite"
    description: "invite to a multiplayer fort"
    aliases:
      - "inv"
  Join:
    permission: "fortgame.multiplayer.join"
    description: "join player to fort"
